### ISSUE TITLE
step 2.1.1.1 timesync daemon failed sometimes.

### ISSUE THREAD

**Issue by elgormush** [ansible-lockdown/UBUNTU22-CIS-Audit#19]
**Describe the Issue**

This error occurs when the benchmark attempts to enforce a single time synchronization daemon, specifically the systemd-timesyncd service.

**Expected Behavior**

`    amazon-ebs.AWS_AMI_Builder: TASK [UBUNTU22-CIS : 2.1.1.1 | PATCH | Ensure a single time synchronization daemon is in use | mask service] ***
    amazon-ebs.AWS_AMI_Builder: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service systemd-timesyncd.service: host"}`

my configuration is:

`     ubtu22cis_time_sync_tool: ntp
    ubtu22cis_time_servers:
      - name: "169.254.169.123"
        options: "minpoll 8"`

But sometimes the benchmark crashes this step.

**Actual Behavior**
The benchmark process fails with the following error message:
Could not find the requested service systemd-timesyncd.service: host

**Control(s) Affected**
This issue affects Control 2.1.1.1 of the CIS benchmark, which is related to time synchronization and the enforcement of a single time synchronization daemon.

**Environment (please complete the following information):**

- branch being used: [devel
- Ansible Version: 2.15.4
- Host Python Version: [Python 3.10.12]
- Ansible Server Python Version: [3.10.12]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**

**Comment by uk-bolly** [comment]
hi @elgormush 

Thank you for taking the time to raise this issue. I believe the issue is related to Ansible playbook its self and the remediation of your system. This repository if for the audit that can take place if requested.
With regard to the error, this fix should now be in Devel branch for the remediation section.

Please let us know if we have misunderstood anything?

many thanks

uk-bolly
